// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbPhOCx7wcrm_Y_z6FtR5lMKYhKkPSOsk',
    appId: '1:849755045068:web:58117347d73531133f1669',
    messagingSenderId: '849755045068',
    projectId: 'linear-encoder-194119',
    authDomain: 'linear-encoder-194119.firebaseapp.com',
    storageBucket: 'linear-encoder-194119.appspot.com',
    measurementId: 'G-PPC31F3GJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATsODpIECJmajG18DB9cTYmLaNzO6XwjM',
    appId: '1:849755045068:android:650bd03e832ea01e3f1669',
    messagingSenderId: '849755045068',
    projectId: 'linear-encoder-194119',
    storageBucket: 'linear-encoder-194119.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGGywO77CFFfHV0xyXalEtghebaOUU8dE',
    appId: '1:849755045068:ios:3e8143f578d40e223f1669',
    messagingSenderId: '849755045068',
    projectId: 'linear-encoder-194119',
    storageBucket: 'linear-encoder-194119.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGGywO77CFFfHV0xyXalEtghebaOUU8dE',
    appId: '1:849755045068:ios:951d6c944fb509a13f1669',
    messagingSenderId: '849755045068',
    projectId: 'linear-encoder-194119',
    storageBucket: 'linear-encoder-194119.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
